CREATE TABLE user
(
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    nip VARCHAR(250) NOT NULL,
    pesel VARCHAR(15) NOT NULL,
    isAdmin TINYINT(1) DEFAULT '0'
);
CREATE TABLE post
(
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    text VARCHAR(256) NOT NULL
);
